name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'
jobs:
  build:
    name: Build Docker
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Get bashbrew
        run: |
          git clone https://github.com/docker-library/bashbrew.git bashbrew
          chmox +x bashbrew/bashbrew.sh
          ./bashbrew/bashbrew.sh build lingmo
